defaults:
  - dataset: openpack-2d-kpt
  - override hydra/job_logging: custom
  - _self_
datarootdir: /mnt/data3/chai/openpack_dataset/journal_v0.3.1
issue: "Name_of_experiment"
hydra:
  run:
    dir: ${path.logdir.rootdir}
  job:
    chdir: true
debug: true
mode: "train"
model:
  name: "CTRGCN4Seg"
device: [0]
bone: False
alpha: 1
temporal_kernel: None
dilations: None
train:
  num_workers: 3
  batch_size: 8
  epochs: 100
  window: 900 # 15 * 60s
  optimizer:
    type: "Adam"
    lr: 0.01
    weight_decay: 0.0001
    step: [50,75]

  debug:
    batch_size: 8
    epochs: 10
path:
  openpack:
    version: v0.3.1
    rootdir: /mnt/data3/chai/openpack_dataset/journal_v0.3.1

  logdir:
    rootdir: ${datarootdir}/log/${dataset.name}/${model.name}/${issue}
    model: ${path.logdir.rootdir}/model.pth
    predict: ${path.logdir.rootdir}/pred/{user}-{session}
    summary:
      test: ${path.logdir.rootdir}/summary.csv
      submission: ${path.logdir.rootdir}/summary_submission.csv





